# This playbook will have multiple tasks
---
- hosts: all
  tasks:
  - name: This task will ping target servers
    action: ping
  - name: This task will give me OS of my worker machines
    shell: uname
