# This Playbook deploys PHP application to desired Servers
# This playbook also helps us to understand SERVICE HANDLERS
# This Playbook will also help us to learn Variables
---
- hosts: production
  become: true

  vars:
    app_dest: "/var/www/html/index.php"   
    path_ini: "/etc/php/7.4/cli/php.ini"

  tasks:
    - name: Lets Upload PHP application
      copy:
        src: index.php
        dest: "{{ app_dest }}"
        mode: 0755
#  notify is used for service handlers        
      notify: restart apache2 
      
    - name: Configure php.ini file
      lineinfile:
#        path: /etc/php/7.4/cli/php.ini
        path: "{{ path_ini }}"
        regexp: ^short_open_tag
        line: 'short_open_tag-On'
# Lets utilize notfiy name here      
  handlers:      
    - name: restart apache2
      service: name=apache2 state=started 
